name: guardian_angel_v1
description: "Projeto do Semestre de Desenvolvimento de Aplicações Móveis 2024/2025"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Hive para storage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8

  # Acelerometro
  sensors_plus: ^3.0.0
  vibration: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Gerador p/ Hive
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/guardiansoslogo.png
