name: guardian_angel_v1
description: "Projeto do Semestre de Desenvolvimento de Aplicações Móveis 2024/2025"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Hive para storage local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Acelerometro
  sensors_plus: ^3.0.0
  vibration: ^3.1.3

  geolocator: ^9.0.2              # para obter GPS
  camera: ^0.10.0+4               # para câmera / vídeo
  path_provider: ^2.0.11          # para gravar temporariamente
  flutter_email_sender: ^6.0.0    # para enviar e‐mail
  url_launcher: ^6.1.7            # para abrir SMS / WhatsApp
  battery_plus: ^6.2.1            # para obter o nível da bateria
  geocoding: ^3.0.0               # para obter o endereço a partir do GPS
  google_maps_flutter: ^2.12.2    # para mostrar o mapa

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Gerador p/ Hive
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/guardiansoslogo.png
